%% Box Wing Polar from AVL for Verification
[alpha_AVL, CL_AVL, CD_AVL] = AVLDragPolar("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/CFD/Polars/BoxWing.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/CFD/Polars/BoxWingAVLPolar", ...
    [""], ...
    -5, ...
    15, ...
    NaN)

%% CFD Polar
polar = readtable("/Users/michaelchen/Documents/M-Fly/2023/CFD/Polars/CFD Polars for MX-9 and QM-3 - Box Wing w_ PADA.csv");
alpha_CFD = polar.alpha;
CD_CFD = polar.CD;
CL_CFD = polar.CL;

%% Plot polars
figure(1);
plot(CD_AVL, CL_AVL, "o", CD_CFD, CL_CFD, "x", LineWidth=3);
