%% Wing stall
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade3/MX-9C_NOCLAF.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade3/StallTest", ...
    [""], ...
    1.14, ...
    13.59, ...
    ch10sm(false), ...
    5, ...
    NaN)

%% Transition stall CH10
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade3/MX-9C_NOCLAF.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade3/StallTest", ...
    [""], ...
    1.14, ...
    13, ...
    ch10sm(false), ...
    3, ...
    NaN)

%% Fuselage stall NACA 23012
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade3/MX-9C_NOCLAF.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade3/StallTest", ...
    [""], ...
    1.14, ...
    13, ...
    NACA23012(false), ...
    1, ...
    NaN)

%% Wing stall Box Wing
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/CFD/Polars/BoxWing_NOCLAF.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/CFD/Polars/BoXWingStall", ...
    [""], ...
    1.14, ...
    13, ...
    ch10sm(false), ...
    1, ...
    NaN)