%% Wing stall
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_TipChordChangeAndStraightAileron/MX-9D1_NOCLAF.avl", ...
    "//Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_TipChordChangeAndStraightAileron/Stall", ...
    [""], ...
    1.14, ...
    13.59, ...
    0.6124, ...
    13, ...
    ch10sm(false), ...
    1, ...
    NaN)