%% Wing stall
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade2/QM-3B.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade2//StallTest", ...
    [""], ...
    1.14, ...
    13, ...
    HS520(false), ...
    5, ...
    NaN)