%% Wing stall
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade2/QM-3B.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade2//StallTest", ...
    [""], ...
    1.14, ...
    13, ...
    HS520(false), ...
    5, ...
    NaN)

%% New function
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
"/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade5/QM-3E.avl", ...
"/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade5/StallTest", ...
["d2 pm 0\n"], ...
1.14, ...
0.4536, ...
0.1043, ...
7, ...
HS520(false), ...
5, ...
NaN)

%% New function
findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
"/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade5/QM-3E.avl", ...
"/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade5/StallTest", ...
["d2 pm 0\n"], ...
1.14, ...
0.4536, ...
0.1043, ...
7, ...
NACA23118(false), ...
1, ...
NaN)