% AVLCheckForStall(16 , "/Users/michaelchen/Documents/M-Fly", ...
%     "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade2_refinement/MX-9B1.avl", ...
%     "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade2_refinement", ...
%     ["d1 pm 0\n"], ...
%     1.14, ...
%     13, ...
%     ch10sm(false), ...
%     5, ...
%     NaN)

findStallAngle("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade2_refinement/MX-9B1.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade2_refinement/StallTest", ...
    ["d1 pm 0\n"], ...
    1.14, ...
    13, ...
    ch10sm(false), ...
    5, ...
    NaN)

%%

[alpha, CL, CD] = AVLDragPolar("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade2/QM-3B.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade2/Polar", ...
    [""], ...
    -5, ...
    20, ...
    NaN)

figure();
plot(CD, CL, "o", LineWidth=3);

%%

[alpha, CL, CD] = AVLDragPolar("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade2_refinement/MX-9B1.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/MX-9/PA_Trade2_refinement/Polar", ...
    [""], ...
    -5, ...
    15, ...
    NaN)

figure();
plot(CD, CL, "o", LineWidth=3);

%% QM-3A

[alpha, CL, CD] = AVLDragPolar("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade1/QM-3A.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade1/Polar", ...
    [""], ...
    -5, ...
    17, ...
    NaN)

figure();
plot(CD, CL, "o", LineWidth=3);

%% QM-3A1

[alpha, CL, CD] = AVLDragPolar("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade1/QM-3A1.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade1/PolarA1", ...
    [""], ...
    -5, ...
    17, ...
    NaN)

figure();
plot(CD, CL, "o", LineWidth=3);

%% QM-3D

[alpha, CL, CD] = AVLDragPolar("/Users/michaelchen/Documents/M-Fly", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade4/QM-3D.avl", ...
    "/Users/michaelchen/Documents/M-Fly/2023/QM-3/PADA_Trade4/Polar", ...
    [""], ...
    -5, ...
    17, ...
    NaN)

figure();
plot(CD, CL, "o", LineWidth=3);

%%
polar = readtable("/Users/michaelchen/Documents/M-Fly/2023/CFD/Polars/CFD Polars for MX-9 and QM-3 - Box Wing w_ PADA.csv");
alpha = polar.alpha;
CD = polar.CD;
CL = polar.CL;
%%
thrustCurve = @(v) 55.3 - 1.99 * v - 0.0277 * v.^2;
[cruiseVelSpline, MTOWSpline] = findMTOWCruiseVel(alpha, CL, CD, thrustCurve, 1.14, 1.4976);

a = linspace(-5, 17, 50);

figure();
yyaxis left
% plot(a, ppval(cruiseVelSpline, a), [16.3281, 16.3281, 16.3281, 16.3281, 16.4844, 16.4844, 16.4844], [11,12,13,14,15,16,17], LineWidth=2);
plot(a, ppval(cruiseVelSpline, a), LineWidth=2);
xlabel("Angle of attack (deg)");
ylabel("Cruise velocity (m/s)")

yyaxis right
plot(a, ppval(MTOWSpline, a) .* 2.20462, LineWidth=2);
ylabel("MTOW (lb)")