 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.05932     Cltot =  -0.23305     Cl'tot =  -0.23349
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.60316     Cntot =  -0.02292     Cn'tot =   0.01790

  CLtot =   0.60430
  CDtot =   0.04631
  CDvis =   0.01798     CDind = 0.0283344
  CLff  =   0.60929     CDff  = 0.0264543    | Trefftz
  CYff  =   0.00000         e =    0.9211    | Plane  

   Aileron         =   0.00000
   Elevator        =  -9.99398

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.786662    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.017987
 x' mom.  Cl'|    Cla =  -1.463125    Clb =  -0.121012
 y  mom.  Cm |    Cma =  -0.321181    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.164176    Cnb =   0.021686

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.962041    CLq =   4.629278    CLr =  -0.931740
 y  force CY |    CYp =   0.231631    CYq =   0.000000    CYr =  -0.039533
 x' mom.  Cl'|    Clp =  -1.488601    Clq =  -1.788703    Clr =   0.491067
 y  mom.  Cm |    Cmp =  -0.248202    Cmq =  -1.224555    Cmr =   0.000109
 z' mom.  Cn'|    Cnp =  -0.109733    Cnq =   0.193702    Cnr =  -0.047621

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011604
 y  force CY |   CYd01 =  -0.000046   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003184   Cld02 =  -0.004514
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005467
 z' mom.  Cn'|   Cnd01 =  -0.000142   Cnd02 =  -0.000217
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000533
 span eff.   |    ed01 =  -0.000000    ed02 =   0.017169



 Neutral point  Xnp =   0.096940

 Clb Cnr / Clr Cnb  =   0.541141    (  > 1 if spirally stable )
