 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.50000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09682     Cltot =  -0.28375     Cl'tot =  -0.28512
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.73437     Cntot =  -0.03741     Cn'tot =   0.02489

  CLtot =   0.73792
  CDtot =   0.06442
  CDvis =   0.02204     CDind = 0.0423823
  CLff  =   0.74731     CDff  = 0.0399195    | Trefftz
  CYff  =   0.00000         e =    0.9183    | Plane  

   Aileron         =   0.00000
   Elevator        = -12.58122

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.719856    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.022037
 x' mom.  Cl'|    Cla =  -1.437312    Clb =  -0.146741
 y  mom.  Cm |    Cma =  -0.322278    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.196629    Cnb =   0.033033

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.924407    CLq =   4.594604    CLr =  -1.137233
 y  force CY |    CYp =   0.282180    CYq =   0.000000    CYr =  -0.060708
 x' mom.  Cl'|    Clp =  -1.471427    Clq =  -1.775305    Clr =   0.599036
 y  mom.  Cm |    Cmp =  -0.249050    Cmq =  -1.215466    Cmr =   0.000273
 z' mom.  Cn'|    Cnp =  -0.137786    Cnq =   0.235490    Cnr =  -0.066977

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011396
 y  force CY |   CYd01 =  -0.000056   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003136   Cld02 =  -0.004447
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005380
 z' mom.  Cn'|   Cnd01 =  -0.000190   Cnd02 =  -0.000283
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000638
 span eff.   |    ed01 =  -0.000000    ed02 =   0.014098



 Neutral point  Xnp =   0.097224

 Clb Cnr / Clr Cnb  =   0.496676    (  > 1 if spirally stable )
