 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  13.75000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.11848     Cltot =  -0.30841     Cl'tot =  -0.31045
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.79819     Cntot =  -0.04578     Cn'tot =   0.02884

  CLtot =   0.80347
  CDtot =   0.07464
  CDvis =   0.02433     CDind = 0.0503071
  CLff  =   0.81578     CDff  = 0.0476260    | Trefftz
  CYff  =   0.00000         e =    0.9172    | Plane  

   Aileron         =   0.00000
   Elevator        = -13.89535

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.681982    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.024324
 x' mom.  Cl'|    Cla =  -1.422678    Clb =  -0.159210
 y  mom.  Cm |    Cma =  -0.322937    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.211670    Cnb =   0.039550

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.903034    CLq =   4.574696    CLr =  -1.237960
 y  force CY |    CYp =   0.306721    CYq =   0.000000    CYr =  -0.072884
 x' mom.  Cl'|    Clp =  -1.461703    Clq =  -1.767613    Clr =   0.652017
 y  mom.  Cm |    Cmp =  -0.249559    Cmq =  -1.210194    Cmr =   0.000388
 z' mom.  Cn'|    Cnp =  -0.152429    Cnq =   0.255759    Cnr =  -0.077864

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011277
 y  force CY |   CYd01 =  -0.000061   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003109   Cld02 =  -0.004409
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005329
 z' mom.  Cn'|   Cnd01 =  -0.000214   Cnd02 =  -0.000316
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000689
 span eff.   |    ed01 =  -0.000000    ed02 =   0.012926



 Neutral point  Xnp =   0.097391

 Clb Cnr / Clr Cnb  =   0.480729    (  > 1 if spirally stable )
