 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  14.37500     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.13002     Cltot =  -0.32055     Cl'tot =  -0.32298
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.82960     Cntot =  -0.05024     Cn'tot =   0.03092

  CLtot =   0.83590
  CDtot =   0.08002
  CDvis =   0.02554     CDind = 0.0544786
  CLff  =   0.84986     CDff  = 0.0517164    | Trefftz
  CYff  =   0.00000         e =    0.9167    | Plane  

   Aileron         =   0.00000
   Elevator        = -14.55827

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.661988    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.025530
 x' mom.  Cl'|    Cla =  -1.414953    Clb =  -0.165335
 y  mom.  Cm |    Cma =  -0.323295    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.218869    Cnb =   0.043014

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.891740    CLq =   4.564115    CLr =  -1.287771
 y  force CY |    CYp =   0.318788    CYq =   0.000000    CYr =  -0.079359
 x' mom.  Cl'|    Clp =  -1.456572    Clq =  -1.763525    Clr =   0.678234
 y  mom.  Cm |    Cmp =  -0.249835    Cmq =  -1.207377    Cmr =   0.000455
 z' mom.  Cn'|    Cnp =  -0.159916    Cnq =   0.265721    Cnr =  -0.083588

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011214
 y  force CY |   CYd01 =  -0.000063   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003094   Cld02 =  -0.004388
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005302
 z' mom.  Cn'|   Cnd01 =  -0.000226   Cnd02 =  -0.000332
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000714
 span eff.   |    ed01 =  -0.000000    ed02 =   0.012407



 Neutral point  Xnp =   0.097481

 Clb Cnr / Clr Cnb  =   0.473712    (  > 1 if spirally stable )
