 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  14.68750     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.13596     Cltot =  -0.32656     Cl'tot =  -0.32921
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.84517     Cntot =  -0.05253     Cn'tot =   0.03198

  CLtot =   0.85203
  CDtot =   0.08277
  CDvis =   0.02616     CDind = 0.0566145
  CLff  =   0.86686     CDff  = 0.0538200    | Trefftz
  CYff  =   0.00000         e =    0.9165    | Plane  

   Aileron         =   0.00000
   Elevator        = -14.89130

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.651735    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.026147
 x' mom.  Cl'|    Cla =  -1.410991    Clb =  -0.168369
 y  mom.  Cm |    Cma =  -0.323481    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.222384    Cnb =   0.044797

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.885945    CLq =   4.558670    CLr =  -1.312533
 y  force CY |    CYp =   0.324768    CYq =   0.000000    CYr =  -0.082691
 x' mom.  Cl'|    Clp =  -1.453941    Clq =  -1.761421    Clr =   0.691271
 y  mom.  Cm |    Cmp =  -0.249979    Cmq =  -1.205924    Cmr =   0.000490
 z' mom.  Cn'|    Cnp =  -0.163702    Cnq =   0.270657    Cnr =  -0.086516

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011181
 y  force CY |   CYd01 =  -0.000064   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003086   Cld02 =  -0.004377
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005288
 z' mom.  Cn'|   Cnd01 =  -0.000232   Cnd02 =  -0.000340
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000726
 span eff.   |    ed01 =  -0.000000    ed02 =   0.012162



 Neutral point  Xnp =   0.097528

 Clb Cnr / Clr Cnb  =   0.470394    (  > 1 if spirally stable )
