 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  14.76560     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.13747     Cltot =  -0.32806     Cl'tot =  -0.33077
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.84905     Cntot =  -0.05312     Cn'tot =   0.03225

  CLtot =   0.85605
  CDtot =   0.08347
  CDvis =   0.02631     CDind = 0.0571534
  CLff  =   0.87111     CDff  = 0.0543518    | Trefftz
  CYff  =   0.00000         e =    0.9164    | Plane  

   Aileron         =   0.00000
   Elevator        = -14.97469

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.649146    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.026303
 x' mom.  Cl'|    Cla =  -1.409991    Clb =  -0.169124
 y  mom.  Cm |    Cma =  -0.323528    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.223254    Cnb =   0.045248

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.884482    CLq =   4.557293    CLr =  -1.318707
 y  force CY |    CYp =   0.326257    CYq =   0.000000    CYr =  -0.083534
 x' mom.  Cl'|    Clp =  -1.453277    Clq =  -1.760889    Clr =   0.694521
 y  mom.  Cm |    Cmp =  -0.250016    Cmq =  -1.205556    Cmr =   0.000500
 z' mom.  Cn'|    Cnp =  -0.164653    Cnq =   0.271886    Cnr =  -0.087255

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011173
 y  force CY |   CYd01 =  -0.000065   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003084   Cld02 =  -0.004374
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005285
 z' mom.  Cn'|   Cnd01 =  -0.000233   Cnd02 =  -0.000342
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000730
 span eff.   |    ed01 =  -0.000000    ed02 =   0.012102



 Neutral point  Xnp =   0.097540

 Clb Cnr / Clr Cnb  =   0.469583    (  > 1 if spirally stable )
