 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  14.84380     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.13898     Cltot =  -0.32956     Cl'tot =  -0.33232
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.85293     Cntot =  -0.05370     Cn'tot =   0.03252

  CLtot =   0.86007
  CDtot =   0.08416
  CDvis =   0.02647     CDind = 0.0576950
  CLff  =   0.87536     CDff  = 0.0548866    | Trefftz
  CYff  =   0.00000         e =    0.9163    | Plane  

   Aileron         =   0.00000
   Elevator        = -15.05826

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.646544    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.026460
 x' mom.  Cl'|    Cla =  -1.408985    Clb =  -0.169879
 y  mom.  Cm |    Cma =  -0.323576    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.224122    Cnb =   0.045701

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.883010    CLq =   4.555908    CLr =  -1.324882
 y  force CY |    CYp =   0.327745    CYq =   0.000000    CYr =  -0.084382
 x' mom.  Cl'|    Clp =  -1.452610    Clq =  -1.760354    Clr =   0.697773
 y  mom.  Cm |    Cmp =  -0.250052    Cmq =  -1.205186    Cmr =   0.000509
 z' mom.  Cn'|    Cnp =  -0.165606    Cnq =   0.273115    Cnr =  -0.087997

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011164
 y  force CY |   CYd01 =  -0.000065   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003083   Cld02 =  -0.004372
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005281
 z' mom.  Cn'|   Cnd01 =  -0.000235   Cnd02 =  -0.000344
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000733
 span eff.   |    ed01 =  -0.000000    ed02 =   0.012042



 Neutral point  Xnp =   0.097552

 Clb Cnr / Clr Cnb  =   0.468777    (  > 1 if spirally stable )
