 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  14.92190     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.14050     Cltot =  -0.33106     Cl'tot =  -0.33387
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.85679     Cntot =  -0.05429     Cn'tot =   0.03279

  CLtot =   0.86408
  CDtot =   0.08486
  CDvis =   0.02663     CDind = 0.0582380
  CLff  =   0.87960     CDff  = 0.0554232    | Trefftz
  CYff  =   0.00000         e =    0.9163    | Plane  

   Aileron         =   0.00000
   Elevator        = -15.14180

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.643934    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.026617
 x' mom.  Cl'|    Cla =  -1.407977    Clb =  -0.170632
 y  mom.  Cm |    Cma =  -0.323624    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.224985    Cnb =   0.046156

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.881535    CLq =   4.554519    CLr =  -1.331043
 y  force CY |    CYp =   0.329229    CYq =   0.000000    CYr =  -0.085232
 x' mom.  Cl'|    Clp =  -1.451940    Clq =  -1.759817    Clr =   0.701018
 y  mom.  Cm |    Cmp =  -0.250089    Cmq =  -1.204814    Cmr =   0.000519
 z' mom.  Cn'|    Cnp =  -0.166561    Cnq =   0.274340    Cnr =  -0.088741

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011156
 y  force CY |   CYd01 =  -0.000065   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003081   Cld02 =  -0.004369
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005278
 z' mom.  Cn'|   Cnd01 =  -0.000236   Cnd02 =  -0.000346
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000736
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011984



 Neutral point  Xnp =   0.097563

 Clb Cnr / Clr Cnb  =   0.467980    (  > 1 if spirally stable )
