 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  15.39060     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.14977     Cltot =  -0.33998     Cl'tot =  -0.34314
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -0.87988     Cntot =  -0.05787     Cn'tot =   0.03444

  CLtot =   0.88808
  CDtot =   0.08912
  CDvis =   0.02758     CDind = 0.0615381
  CLff  =   0.90502     CDff  = 0.0586936    | Trefftz
  CYff  =   0.00000         e =    0.9160    | Plane  

   Aileron         =   0.00000
   Elevator        = -15.64456

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.628058    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.027572
 x' mom.  Cl'|    Cla =  -1.401842    Clb =  -0.175123
 y  mom.  Cm |    Cma =  -0.323918    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.230087    Cnb =   0.048930

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.872556    CLq =   4.546047    CLr =  -1.367886
 y  force CY |    CYp =   0.338088    CYq =   0.000000    CYr =  -0.090420
 x' mom.  Cl'|    Clp =  -1.447868    Clq =  -1.756543    Clr =   0.720424
 y  mom.  Cm |    Cmp =  -0.250317    Cmq =  -1.202545    Cmr =   0.000578
 z' mom.  Cn'|    Cnp =  -0.172325    Cnq =   0.281650    Cnr =  -0.093262

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011106
 y  force CY |   CYd01 =  -0.000067   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003069   Cld02 =  -0.004352
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005256
 z' mom.  Cn'|   Cnd01 =  -0.000245   Cnd02 =  -0.000358
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000754
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011642



 Neutral point  Xnp =   0.097637

 Clb Cnr / Clr Cnb  =   0.463325    (  > 1 if spirally stable )
