 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  15.31250     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.14821     Cltot =  -0.33850     Cl'tot =  -0.34160
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -0.87605     Cntot =  -0.05727     Cn'tot =   0.03416

  CLtot =   0.88409
  CDtot =   0.08841
  CDvis =   0.02742     CDind = 0.0609833
  CLff  =   0.90078     CDff  = 0.0581427    | Trefftz
  CYff  =   0.00000         e =    0.9160    | Plane  

   Aileron         =   0.00000
   Elevator        = -15.56060

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.630729    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.027411
 x' mom.  Cl'|    Cla =  -1.402874    Clb =  -0.174378
 y  mom.  Cm |    Cma =  -0.323868    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.229246    Cnb =   0.048462

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.874067    CLq =   4.547474    CLr =  -1.361762
 y  force CY |    CYp =   0.336618    CYq =   0.000000    CYr =  -0.089545
 x' mom.  Cl'|    Clp =  -1.448553    Clq =  -1.757095    Clr =   0.717198
 y  mom.  Cm |    Cmp =  -0.250278    Cmq =  -1.202928    Cmr =   0.000568
 z' mom.  Cn'|    Cnp =  -0.171360    Cnq =   0.280437    Cnr =  -0.092502

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011114
 y  force CY |   CYd01 =  -0.000066   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003071   Cld02 =  -0.004355
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005260
 z' mom.  Cn'|   Cnd01 =  -0.000244   Cnd02 =  -0.000356
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000751
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011698



 Neutral point  Xnp =   0.097624

 Clb Cnr / Clr Cnb  =   0.464085    (  > 1 if spirally stable )
