 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  15.46880     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15134     Cltot =  -0.34146     Cl'tot =  -0.34468
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.88371     Cntot =  -0.05848     Cn'tot =   0.03471

  CLtot =   0.89207
  CDtot =   0.08984
  CDvis =   0.02774     CDind = 0.0620956
  CLff  =   0.90925     CDff  = 0.0592476    | Trefftz
  CYff  =   0.00000         e =    0.9159    | Plane  

   Aileron         =   0.00000
   Elevator        = -15.72869

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.625373    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.027733
 x' mom.  Cl'|    Cla =  -1.400805    Clb =  -0.175868
 y  mom.  Cm |    Cma =  -0.323968    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.230925    Cnb =   0.049400

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.871037    CLq =   4.544611    CLr =  -1.374011
 y  force CY |    CYp =   0.339558    CYq =   0.000000    CYr =  -0.091299
 x' mom.  Cl'|    Clp =  -1.447180    Clq =  -1.755989    Clr =   0.723651
 y  mom.  Cm |    Cmp =  -0.250355    Cmq =  -1.202160    Cmr =   0.000588
 z' mom.  Cn'|    Cnp =  -0.173294    Cnq =   0.282863    Cnr =  -0.094025

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011097
 y  force CY |   CYd01 =  -0.000067   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003067   Cld02 =  -0.004349
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005252
 z' mom.  Cn'|   Cnd01 =  -0.000247   Cnd02 =  -0.000360
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000757
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011587



 Neutral point  Xnp =   0.097649

 Clb Cnr / Clr Cnb  =   0.462569    (  > 1 if spirally stable )
