 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  15.62500     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15450     Cltot =  -0.34441     Cl'tot =  -0.34776
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.89135     Cntot =  -0.05970     Cn'tot =   0.03527

  CLtot =   0.90002
  CDtot =   0.09128
  CDvis =   0.02807     CDind = 0.0632149
  CLff  =   0.91770     CDff  = 0.0603613    | Trefftz
  CYff  =   0.00000         e =    0.9158    | Plane  

   Aileron         =   0.00000
   Elevator        = -15.89695

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.619980    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.028057
 x' mom.  Cl'|    Cla =  -1.398721    Clb =  -0.177352
 y  mom.  Cm |    Cma =  -0.324069    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.232589    Cnb =   0.050345

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.867985    CLq =   4.541725    CLr =  -1.386226
 y  force CY |    CYp =   0.342487    CYq =   0.000000    CYr =  -0.093066
 x' mom.  Cl'|    Clp =  -1.445797    Clq =  -1.754874    Clr =   0.730087
 y  mom.  Cm |    Cmp =  -0.250433    Cmq =  -1.201385    Cmr =   0.000609
 z' mom.  Cn'|    Cnp =  -0.175233    Cnq =   0.285280    Cnr =  -0.095558

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011080
 y  force CY |   CYd01 =  -0.000068   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003063   Cld02 =  -0.004343
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005245
 z' mom.  Cn'|   Cnd01 =  -0.000249   Cnd02 =  -0.000364
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000763
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011478



 Neutral point  Xnp =   0.097674

 Clb Cnr / Clr Cnb  =   0.461076    (  > 1 if spirally stable )
