 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  15.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.14203     Cltot =  -0.33255     Cl'tot =  -0.33542
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.86065     Cntot =  -0.05488     Cn'tot =   0.03306

  CLtot =   0.86809
  CDtot =   0.08557
  CDvis =   0.02678     CDind = 0.0587829
  CLff  =   0.88384     CDff  = 0.0559622    | Trefftz
  CYff  =   0.00000         e =    0.9162    | Plane  

   Aileron         =   0.00000
   Elevator        = -15.22540

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.641314    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.026774
 x' mom.  Cl'|    Cla =  -1.406965    Clb =  -0.171383
 y  mom.  Cm |    Cma =  -0.323672    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.225844    Cnb =   0.046613

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.880054    CLq =   4.553123    CLr =  -1.337198
 y  force CY |    CYp =   0.330711    CYq =   0.000000    CYr =  -0.086087
 x' mom.  Cl'|    Clp =  -1.451268    Clq =  -1.759277    Clr =   0.704259
 y  mom.  Cm |    Cmp =  -0.250127    Cmq =  -1.204441    Cmr =   0.000528
 z' mom.  Cn'|    Cnp =  -0.167517    Cnq =   0.275563    Cnr =  -0.089488

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011148
 y  force CY |   CYd01 =  -0.000065   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003079   Cld02 =  -0.004366
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005274
 z' mom.  Cn'|   Cnd01 =  -0.000238   Cnd02 =  -0.000348
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000739
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011925



 Neutral point  Xnp =   0.097576

 Clb Cnr / Clr Cnb  =   0.467188    (  > 1 if spirally stable )
