 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  16.25000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.16744     Cltot =  -0.35612     Cl'tot =  -0.36000
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.92166     Cntot =  -0.06470     Cn'tot =   0.03754

  CLtot =   0.93170
  CDtot =   0.09716
  CDvis =   0.02939     CDind = 0.0677693
  CLff  =   0.95145     CDff  = 0.0649116    | Trefftz
  CYff  =   0.00000         e =    0.9154    | Plane  

   Aileron         =   0.00000
   Elevator        = -16.57315

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.598006    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.029377
 x' mom.  Cl'|    Cla =  -1.390231    Clb =  -0.183237
 y  mom.  Cm |    Cma =  -0.324485    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.239099    Cnb =   0.054208

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.855545    CLq =   4.529927    CLr =  -1.434845
 y  force CY |    CYp =   0.354108    CYq =   0.000000    CYr =  -0.100292
 x' mom.  Cl'|    Clp =  -1.440162    Clq =  -1.750315    Clr =   0.755711
 y  mom.  Cm |    Cmp =  -0.250755    Cmq =  -1.198211    Cmr =   0.000697
 z' mom.  Cn'|    Cnp =  -0.183068    Cnq =   0.294867    Cnr =  -0.101790

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011009
 y  force CY |   CYd01 =  -0.000070   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003046   Cld02 =  -0.004320
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005214
 z' mom.  Cn'|   Cnd01 =  -0.000261   Cnd02 =  -0.000380
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000787
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011060



 Neutral point  Xnp =   0.097778

 Clb Cnr / Clr Cnb  =   0.455307    (  > 1 if spirally stable )
