 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  16.56250     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.17408     Cltot =  -0.36192     Cl'tot =  -0.36608
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.93668     Cntot =  -0.06726     Cn'tot =   0.03870

  CLtot =   0.94743
  CDtot =   0.10016
  CDvis =   0.03007     CDind = 0.0700907
  CLff  =   0.96828     CDff  = 0.0672427    | Trefftz
  CYff  =   0.00000         e =    0.9152    | Plane  

   Aileron         =   0.00000
   Elevator        = -16.91308

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.586785    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.030051
 x' mom.  Cl'|    Cla =  -1.385895    Clb =  -0.186148
 y  mom.  Cm |    Cma =  -0.324701    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.242264    Cnb =   0.056187

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.849189    CLq =   4.523880    CLr =  -1.458998
 y  force CY |    CYp =   0.359860    CYq =   0.000000    CYr =  -0.103997
 x' mom.  Cl'|    Clp =  -1.437286    Clq =  -1.747979    Clr =   0.768445
 y  mom.  Cm |    Cmp =  -0.250922    Cmq =  -1.196580    Cmr =   0.000743
 z' mom.  Cn'|    Cnp =  -0.187030    Cnq =   0.299612    Cnr =  -0.104965

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010973
 y  force CY |   CYd01 =  -0.000071   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003038   Cld02 =  -0.004308
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005199
 z' mom.  Cn'|   Cnd01 =  -0.000267   Cnd02 =  -0.000388
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000799
 span eff.   |    ed01 =  -0.000000    ed02 =   0.010862



 Neutral point  Xnp =   0.097831

 Clb Cnr / Clr Cnb  =   0.452534    (  > 1 if spirally stable )
