 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  16.71880     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.17744     Cltot =  -0.36481     Cl'tot =  -0.36911
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.94415     Cntot =  -0.06856     Cn'tot =   0.03928

  CLtot =   0.95528
  CDtot =   0.10167
  CDvis =   0.03041     CDind = 0.0712625
  CLff  =   0.97669     CDff  = 0.0684225    | Trefftz
  CYff  =   0.00000         e =    0.9151    | Plane  

   Aileron         =   0.00000
   Elevator        = -17.08356

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.581115    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.030391
 x' mom.  Cl'|    Cla =  -1.383704    Clb =  -0.187596
 y  mom.  Cm |    Cma =  -0.324811    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.243824    Cnb =   0.057190

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.845977    CLq =   4.520819    CLr =  -1.471038
 y  force CY |    CYp =   0.362721    CYq =   0.000000    CYr =  -0.105873
 x' mom.  Cl'|    Clp =  -1.435833    Clq =  -1.746796    Clr =   0.774795
 y  mom.  Cm |    Cmp =  -0.251007    Cmq =  -1.195753    Cmr =   0.000768
 z' mom.  Cn'|    Cnp =  -0.189023    Cnq =   0.301972    Cnr =  -0.106567

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010955
 y  force CY |   CYd01 =  -0.000071   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003033   Cld02 =  -0.004302
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005191
 z' mom.  Cn'|   Cnd01 =  -0.000270   Cnd02 =  -0.000392
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000805
 span eff.   |    ed01 =  -0.000000    ed02 =   0.010765



 Neutral point  Xnp =   0.097858

 Clb Cnr / Clr Cnb  =   0.451172    (  > 1 if spirally stable )
