 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  16.79690     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.17913     Cltot =  -0.36625     Cl'tot =  -0.37062
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.94787     Cntot =  -0.06921     Cn'tot =   0.03958

  CLtot =   0.95919
  CDtot =   0.10243
  CDvis =   0.03058     CDind = 0.0718507
  CLff  =   0.98088     CDff  = 0.0690155    | Trefftz
  CYff  =   0.00000         e =    0.9150    | Plane  

   Aileron         =   0.00000
   Elevator        = -17.16887

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.578268    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.030561
 x' mom.  Cl'|    Cla =  -1.382604    Clb =  -0.188317
 y  mom.  Cm |    Cma =  -0.324866    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.244598    Cnb =   0.057694

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.844363    CLq =   4.519280    CLr =  -1.477044
 y  force CY |    CYp =   0.364147    CYq =   0.000000    CYr =  -0.106816
 x' mom.  Cl'|    Clp =  -1.435103    Clq =  -1.746201    Clr =   0.777962
 y  mom.  Cm |    Cmp =  -0.251050    Cmq =  -1.195337    Cmr =   0.000780
 z' mom.  Cn'|    Cnp =  -0.190021    Cnq =   0.303148    Cnr =  -0.107371

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010946
 y  force CY |   CYd01 =  -0.000072   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003031   Cld02 =  -0.004299
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005187
 z' mom.  Cn'|   Cnd01 =  -0.000271   Cnd02 =  -0.000394
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000808
 span eff.   |    ed01 =  -0.000000    ed02 =   0.010717



 Neutral point  Xnp =   0.097872

 Clb Cnr / Clr Cnb  =   0.450497    (  > 1 if spirally stable )
