 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  16.87500     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.18083     Cltot =  -0.36768     Cl'tot =  -0.37213
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.95159     Cntot =  -0.06987     Cn'tot =   0.03987

  CLtot =   0.96310
  CDtot =   0.10319
  CDvis =   0.03075     CDind = 0.0724406
  CLff  =   0.98508     CDff  = 0.0696108    | Trefftz
  CYff  =   0.00000         e =    0.9150    | Plane  

   Aileron         =   0.00000
   Elevator        = -17.25425

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.575412    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.030733
 x' mom.  Cl'|    Cla =  -1.381500    Clb =  -0.189037
 y  mom.  Cm |    Cma =  -0.324922    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.245368    Cnb =   0.058199

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.842744    CLq =   4.517735    CLr =  -1.483044
 y  force CY |    CYp =   0.365571    CYq =   0.000000    CYr =  -0.107762
 x' mom.  Cl'|    Clp =  -1.434371    Clq =  -1.745604    Clr =   0.781127
 y  mom.  Cm |    Cmp =  -0.251093    Cmq =  -1.194919    Cmr =   0.000792
 z' mom.  Cn'|    Cnp =  -0.191022    Cnq =   0.304322    Cnr =  -0.108178

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010937
 y  force CY |   CYd01 =  -0.000072   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003029   Cld02 =  -0.004296
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005183
 z' mom.  Cn'|   Cnd01 =  -0.000273   Cnd02 =  -0.000396
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000810
 span eff.   |    ed01 =  -0.000000    ed02 =   0.010670



 Neutral point  Xnp =   0.097886

 Clb Cnr / Clr Cnb  =   0.449826    (  > 1 if spirally stable )
