 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  17.50000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.19467     Cltot =  -0.37909     Cl'tot =  -0.38416
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.98110     Cntot =  -0.07522     Cn'tot =   0.04226

  CLtot =   0.99423
  CDtot =   0.10936
  CDvis =   0.03214     CDind = 0.0772232
  CLff  =   1.01858     CDff  = 0.0744567    | Trefftz
  CYff  =   0.00000         e =    0.9146    | Plane  

   Aileron         =   0.00000
   Elevator        = -17.94049

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.552218    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.032122
 x' mom.  Cl'|    Cla =  -1.372539    Clb =  -0.194749
 y  mom.  Cm |    Cma =  -0.325379    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.251390    Cnb =   0.062319

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.829592    CLq =   4.505154    CLr =  -1.530810
 y  force CY |    CYp =   0.376869    CYq =   0.000000    CYr =  -0.115472
 x' mom.  Cl'|    Clp =  -1.428427    Clq =  -1.740743    Clr =   0.806328
 y  mom.  Cm |    Cmp =  -0.251446    Cmq =  -1.191509    Cmr =   0.000896
 z' mom.  Cn'|    Cnp =  -0.199098    Cnq =   0.313640    Cnr =  -0.114713

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010862
 y  force CY |   CYd01 =  -0.000074   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003011   Cld02 =  -0.004270
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005150
 z' mom.  Cn'|   Cnd01 =  -0.000285   Cnd02 =  -0.000412
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000834
 span eff.   |    ed01 =  -0.000000    ed02 =   0.010304



 Neutral point  Xnp =   0.097999

 Clb Cnr / Clr Cnb  =   0.444587    (  > 1 if spirally stable )
