 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  18.75000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.22360     Cltot =  -0.40142     Cl'tot =  -0.40788
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -1.03889     Cntot =  -0.08640     Cn'tot =   0.04722

  CLtot =   1.05563
  CDtot =   0.12221
  CDvis =   0.03511     CDind = 0.0870987
  CLff  =   1.08520     CDff  = 0.0845786    | Trefftz
  CYff  =   0.00000         e =    0.9139    | Plane  

   Aileron         =   0.00000
   Elevator        = -19.32955

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.504135    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.035088
 x' mom.  Cl'|    Cla =  -1.353960    Clb =  -0.205895
 y  mom.  Cm |    Cma =  -0.326421    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.244295    Cnb =   0.070706

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.802361    CLq =   4.478857    CLr =  -1.624986
 y  force CY |    CYp =   0.398951    CYq =  -0.000000    CYr =  -0.131596
 x' mom.  Cl'|    Clp =  -1.416142    Clq =  -1.730582    Clr =   0.856055
 y  mom.  Cm |    Cmp =  -0.252251    Cmq =  -1.184393    Cmr =   0.001166
 z' mom.  Cn'|    Cnp =  -0.231465    Cnq =   0.310048    Cnr =  -0.117471

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010705
 y  force CY |   CYd01 =  -0.000078   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.002971   Cld02 =  -0.004210
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005082
 z' mom.  Cn'|   Cnd01 =  -0.000314   Cnd02 =  -0.000467
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000879
 span eff.   |    ed01 =  -0.000000    ed02 =   0.009638



 Neutral point  Xnp =   0.098241

 Clb Cnr / Clr Cnb  =   0.399596    (  > 1 if spirally stable )
