 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  19.37500     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.23798     Cltot =  -0.41242     Cl'tot =  -0.41957
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -1.06737     Cntot =  -0.09195     Cn'tot =   0.05007

  CLtot =   1.08588
  CDtot =   0.12959
  CDvis =   0.03742     CDind = 0.0921792
  CLff  =   1.11829     CDff  = 0.0898490    | Trefftz
  CYff  =   0.00000         e =    0.9136    | Plane  

   Aileron         =   0.00000
   Elevator        = -20.03350

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.479438    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.037390
 x' mom.  Cl'|    Cla =  -1.344417    Clb =  -0.211323
 y  mom.  Cm |    Cma =  -0.326617    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.250382    Cnb =   0.075187

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.788983    CLq =   4.465171    CLr =  -1.671227
 y  force CY |    CYp =   0.409726    CYq =  -0.000000    CYr =  -0.139998
 x' mom.  Cl'|    Clp =  -1.410129    Clq =  -1.725294    Clr =   0.880500
 y  mom.  Cm |    Cmp =  -0.252403    Cmq =  -1.180217    Cmr =   0.001131
 z' mom.  Cn'|    Cnp =  -0.239534    Cnq =   0.319793    Cnr =  -0.125020

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010624
 y  force CY |   CYd01 =  -0.000080   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.002951   Cld02 =  -0.004181
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005045
 z' mom.  Cn'|   Cnd01 =  -0.000328   Cnd02 =  -0.000485
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000900
 span eff.   |    ed01 =  -0.000000    ed02 =   0.009334



 Neutral point  Xnp =   0.098353

 Clb Cnr / Clr Cnb  =   0.399078    (  > 1 if spirally stable )
