 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  19.68750     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.24498     Cltot =  -0.41791     Cl'tot =  -0.42537
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -1.08158     Cntot =  -0.09466     Cn'tot =   0.05167

  CLtot =   1.10088
  CDtot =   0.13372
  CDvis =   0.03896     CDind = 0.0947522
  CLff  =   1.13478     CDff  = 0.0925353    | Trefftz
  CYff  =   0.00000         e =    0.9134    | Plane  

   Aileron         =   0.00000
   Elevator        = -20.38816

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.466983    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.038938
 x' mom.  Cl'|    Cla =  -1.339605    Clb =  -0.213999
 y  mom.  Cm |    Cma =  -0.327241    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.253898    Cnb =   0.077506

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.782543    CLq =   4.458202    CLr =  -1.694091
 y  force CY |    CYp =   0.415045    CYq =  -0.000000    CYr =  -0.144281
 x' mom.  Cl'|    Clp =  -1.407244    Clq =  -1.722601    Clr =   0.892596
 y  mom.  Cm |    Cmp =  -0.252885    Cmq =  -1.178703    Cmr =   0.001379
 z' mom.  Cn'|    Cnp =  -0.242708    Cnq =   0.325577    Cnr =  -0.129637

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010582
 y  force CY |   CYd01 =  -0.000081   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.002941   Cld02 =  -0.004167
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005028
 z' mom.  Cn'|   Cnd01 =  -0.000332   Cnd02 =  -0.000490
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000911
 span eff.   |    ed01 =  -0.000000    ed02 =   0.009189



 Neutral point  Xnp =   0.098434

 Clb Cnr / Clr Cnb  =   0.401008    (  > 1 if spirally stable )
