 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  19.76560     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.24670     Cltot =  -0.41928     Cl'tot =  -0.42681
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -1.08512     Cntot =  -0.09532     Cn'tot =   0.05208

  CLtot =   1.10462
  CDtot =   0.13480
  CDvis =   0.03940     CDind = 0.0953986
  CLff  =   1.13890     CDff  = 0.0932120    | Trefftz
  CYff  =   0.00000         e =    0.9134    | Plane  

   Aileron         =   0.00000
   Elevator        = -20.47705

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.463861    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.039370
 x' mom.  Cl'|    Cla =  -1.338399    Clb =  -0.214664
 y  mom.  Cm |    Cma =  -0.327316    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.255576    Cnb =   0.078096

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.780964    CLq =   4.456447    CLr =  -1.699777
 y  force CY |    CYp =   0.416367    CYq =   0.000000    CYr =  -0.145360
 x' mom.  Cl'|    Clp =  -1.406537    Clq =  -1.721923    Clr =   0.895605
 y  mom.  Cm |    Cmp =  -0.252943    Cmq =  -1.178226    Cmr =   0.001396
 z' mom.  Cn'|    Cnp =  -0.242860    Cnq =   0.327953    Cnr =  -0.131303

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010572
 y  force CY |   CYd01 =  -0.000082   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.002939   Cld02 =  -0.004164
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005023
 z' mom.  Cn'|   Cnd01 =  -0.000333   Cnd02 =  -0.000490
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000914
 span eff.   |    ed01 =  -0.000000    ed02 =   0.009153



 Neutral point  Xnp =   0.098451

 Clb Cnr / Clr Cnb  =   0.402985    (  > 1 if spirally stable )
