 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  19.84380     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.24841     Cltot =  -0.42065     Cl'tot =  -0.42826
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -1.08867     Cntot =  -0.09598     Cn'tot =   0.05251

  CLtot =   1.10836
  CDtot =   0.13589
  CDvis =   0.03985     CDind = 0.0960471
  CLff  =   1.14302     CDff  = 0.0938916    | Trefftz
  CYff  =   0.00000         e =    0.9133    | Plane  

   Aileron         =   0.00000
   Elevator        = -20.56616

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.460732    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.039820
 x' mom.  Cl'|    Cla =  -1.337189    Clb =  -0.215328
 y  mom.  Cm |    Cma =  -0.327392    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.257247    Cnb =   0.078689

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.779395    CLq =   4.454683    CLr =  -1.705461
 y  force CY |    CYp =   0.417688    CYq =   0.000000    CYr =  -0.146444
 x' mom.  Cl'|    Clp =  -1.405835    Clq =  -1.721242    Clr =   0.898613
 y  mom.  Cm |    Cmp =  -0.253001    Cmq =  -1.177748    Cmr =   0.001414
 z' mom.  Cn'|    Cnp =  -0.243018    Cnq =   0.330327    Cnr =  -0.132988

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010561
 y  force CY |   CYd01 =  -0.000082   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.002937   Cld02 =  -0.004161
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005018
 z' mom.  Cn'|   Cnd01 =  -0.000334   Cnd02 =  -0.000491
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000916
 span eff.   |    ed01 =  -0.000000    ed02 =   0.009117



 Neutral point  Xnp =   0.098467

 Clb Cnr / Clr Cnb  =   0.404972    (  > 1 if spirally stable )
