 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  19.92190     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.25012     Cltot =  -0.42202     Cl'tot =  -0.42970
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -1.09222     Cntot =  -0.09664     Cn'tot =   0.05294

  CLtot =   1.11208
  CDtot =   0.13701
  CDvis =   0.04032     CDind = 0.0966961
  CLff  =   1.14713     CDff  = 0.0945725    | Trefftz
  CYff  =   0.00000         e =    0.9133    | Plane  

   Aileron         =   0.00000
   Elevator        = -20.65526

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.457603    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.040288
 x' mom.  Cl'|    Cla =  -1.335980    Clb =  -0.215990
 y  mom.  Cm |    Cma =  -0.327467    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.258908    Cnb =   0.079283

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.777841    CLq =   4.452917    CLr =  -1.711125
 y  force CY |    CYp =   0.419004    CYq =   0.000000    CYr =  -0.147530
 x' mom.  Cl'|    Clp =  -1.405140    Clq =  -1.720559    Clr =   0.901612
 y  mom.  Cm |    Cmp =  -0.253060    Cmq =  -1.177268    Cmr =   0.001431
 z' mom.  Cn'|    Cnp =  -0.243181    Cnq =   0.332694    Cnr =  -0.134687

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010551
 y  force CY |   CYd01 =  -0.000082   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.002934   Cld02 =  -0.004158
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005014
 z' mom.  Cn'|   Cnd01 =  -0.000335   Cnd02 =  -0.000491
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000919
 span eff.   |    ed01 =  -0.000000    ed02 =   0.009082



 Neutral point  Xnp =   0.098484

 Clb Cnr / Clr Cnb  =   0.406966    (  > 1 if spirally stable )
