 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.50000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00501     Cltot =  -0.07316     Cl'tot =  -0.07300
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.18934     Cntot =   0.00194     Cn'tot =   0.00513

  CLtot =   0.18894
  CDtot =   0.01326
  CDvis =   0.01056     CDind = 0.0027087
  CLff  =   0.18906     CDff  = 0.0024689    | Trefftz
  CYff  =   0.00000         e =    0.9503    | Plane  

   Aileron         =   0.00000
   Elevator        =  -2.44927

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.907375    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.010591
 x' mom.  Cl'|    Cla =  -1.509768    Clb =  -0.039343
 y  mom.  Cm |    Cma =  -0.319527    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.052804    Cnb =   0.001842

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.029786    CLq =   4.690033    CLr =  -0.291664
 y  force CY |    CYp =   0.071650    CYq =   0.000000    CYr =  -0.002697
 x' mom.  Cl'|    Clp =  -1.519817    Clq =  -1.812178    Clr =   0.155441
 y  mom.  Cm |    Cmp =  -0.246924    Cmq =  -1.239933    Cmr =  -0.000019
 z' mom.  Cn'|    Cnp =  -0.033053    Cnq =   0.061129    Cnr =  -0.012034

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011964
 y  force CY |   CYd01 =  -0.000015   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003263   Cld02 =  -0.004626
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005613
 z' mom.  Cn'|   Cnd01 =   0.000004   Cnd02 =  -0.000018
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000195
 span eff.   |    ed01 =  -0.000000    ed02 =   0.045290



 Neutral point  Xnp =   0.096465

 Clb Cnr / Clr Cnb  =   1.653205    (  > 1 if spirally stable )
