 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.57810     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00472     Cltot =  -0.07486     Cl'tot =  -0.07470
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.19375     Cntot =   0.00182     Cn'tot =   0.00519

  CLtot =   0.19334
  CDtot =   0.01343
  CDvis =   0.01059     CDind = 0.0028373
  CLff  =   0.19347     CDff  = 0.0025876    | Trefftz
  CYff  =   0.00000         e =    0.9494    | Plane  

   Aileron         =   0.00000
   Elevator        =  -2.52686

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.906776    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.010629
 x' mom.  Cl'|    Cla =  -1.509536    Clb =  -0.040215
 y  mom.  Cm |    Cma =  -0.319533    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.054035    Cnb =   0.001936

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.029451    CLq =   4.689746    CLr =  -0.298448
 y  force CY |    CYp =   0.073356    CYq =   0.000000    CYr =  -0.002868
 x' mom.  Cl'|    Clp =  -1.519660    Clq =  -1.812067    Clr =   0.158995
 y  mom.  Cm |    Cmp =  -0.246928    Cmq =  -1.239866    Cmr =  -0.000019
 z' mom.  Cn'|    Cnp =  -0.033813    Cnq =   0.062546    Cnr =  -0.012214

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011962
 y  force CY |   CYd01 =  -0.000016   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003263   Cld02 =  -0.004626
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005613
 z' mom.  Cn'|   Cnd01 =   0.000002   Cnd02 =  -0.000020
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000199
 span eff.   |    ed01 =  -0.000000    ed02 =   0.044621



 Neutral point  Xnp =   0.096467

 Clb Cnr / Clr Cnb  =   1.595954    (  > 1 if spirally stable )
