 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.65620     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00442     Cltot =  -0.07656     Cl'tot =  -0.07640
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.19815     Cntot =   0.00171     Cn'tot =   0.00526

  CLtot =   0.19773
  CDtot =   0.01360
  CDvis =   0.01063     CDind = 0.0029688
  CLff  =   0.19787     CDff  = 0.0027092    | Trefftz
  CYff  =   0.00000         e =    0.9486    | Plane  

   Aileron         =   0.00000
   Elevator        =  -2.60447

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.906162    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.010667
 x' mom.  Cl'|    Cla =  -1.509299    Clb =  -0.041087
 y  mom.  Cm |    Cma =  -0.319538    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.055264    Cnb =   0.002032

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.029109    CLq =   4.689451    CLr =  -0.305229
 y  force CY |    CYp =   0.075062    CYq =   0.000000    CYr =  -0.003044
 x' mom.  Cl'|    Clp =  -1.519499    Clq =  -1.811953    Clr =   0.162548
 y  mom.  Cm |    Cmp =  -0.246932    Cmq =  -1.239797    Cmr =  -0.000019
 z' mom.  Cn'|    Cnp =  -0.034574    Cnq =   0.063961    Cnr =  -0.012399

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011960
 y  force CY |   CYd01 =  -0.000016   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003262   Cld02 =  -0.004625
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005612
 z' mom.  Cn'|   Cnd01 =   0.000001   Cnd02 =  -0.000022
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000202
 span eff.   |    ed01 =  -0.000000    ed02 =   0.043966



 Neutral point  Xnp =   0.096470

 Clb Cnr / Clr Cnb  =   1.542668    (  > 1 if spirally stable )
