 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.81250     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00380     Cltot =  -0.07997     Cl'tot =  -0.07980
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.20696     Cntot =   0.00147     Cn'tot =   0.00539

  CLtot =   0.20653
  CDtot =   0.01395
  CDvis =   0.01071     CDind = 0.0032412
  CLff  =   0.20669     CDff  = 0.0029609    | Trefftz
  CYff  =   0.00000         e =    0.9470    | Plane  

   Aileron         =   0.00000
   Elevator        =  -2.75982

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.904892    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.010746
 x' mom.  Cl'|    Cla =  -1.508808    Clb =  -0.042832
 y  mom.  Cm |    Cma =  -0.319550    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.057722    Cnb =   0.002231

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.028399    CLq =   4.688838    CLr =  -0.318797
 y  force CY |    CYp =   0.078475    CYq =   0.000000    CYr =  -0.003408
 x' mom.  Cl'|    Clp =  -1.519166    Clq =  -1.811716    Clr =   0.169656
 y  mom.  Cm |    Cmp =  -0.246941    Cmq =  -1.239653    Cmr =  -0.000020
 z' mom.  Cn'|    Cnp =  -0.036097    Cnq =   0.066793    Cnr =  -0.012781

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011957
 y  force CY |   CYd01 =  -0.000017   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003262   Cld02 =  -0.004624
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005611
 z' mom.  Cn'|   Cnd01 =  -0.000002   Cnd02 =  -0.000027
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000210
 span eff.   |    ed01 =  -0.000000    ed02 =   0.042693



 Neutral point  Xnp =   0.096474

 Clb Cnr / Clr Cnb  =   1.446549    (  > 1 if spirally stable )
