 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  20.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.25181     Cltot =  -0.42339     Cl'tot =  -0.43114
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -1.09576     Cntot =  -0.09730     Cn'tot =   0.05338

  CLtot =   1.11581
  CDtot =   0.13815
  CDvis =   0.04080     CDind = 0.0973463
  CLff  =   1.15124     CDff  = 0.0952554    | Trefftz
  CYff  =   0.00000         e =    0.9133    | Plane  

   Aileron         =   0.00000
   Elevator        = -20.74446

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.454470    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.040774
 x' mom.  Cl'|    Cla =  -1.334770    Clb =  -0.216650
 y  mom.  Cm |    Cma =  -0.327543    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.260560    Cnb =   0.079879

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.776298    CLq =   4.451145    CLr =  -1.716779
 y  force CY |    CYp =   0.420317    CYq =   0.000000    CYr =  -0.148619
 x' mom.  Cl'|    Clp =  -1.404451    Clq =  -1.719874    Clr =   0.904606
 y  mom.  Cm |    Cmp =  -0.253118    Cmq =  -1.176787    Cmr =   0.001449
 z' mom.  Cn'|    Cnp =  -0.243351    Cnq =   0.335056    Cnr =  -0.136403

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010540
 y  force CY |   CYd01 =  -0.000082   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.002932   Cld02 =  -0.004155
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005009
 z' mom.  Cn'|   Cnd01 =  -0.000336   Cnd02 =  -0.000492
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000922
 span eff.   |    ed01 =  -0.000000    ed02 =   0.009047



 Neutral point  Xnp =   0.098501

 Clb Cnr / Clr Cnb  =   0.408967    (  > 1 if spirally stable )
