 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.12500     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00247     Cltot =  -0.08677     Cl'tot =  -0.08659
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.22457     Cntot =   0.00095     Cn'tot =   0.00568

  CLtot =   0.22410
  CDtot =   0.01470
  CDvis =   0.01088     CDind = 0.0038219
  CLff  =   0.22431     CDff  = 0.0034978    | Trefftz
  CYff  =   0.00000         e =    0.9442    | Plane  

   Aileron         =   0.00000
   Elevator        =  -3.07054

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.902180    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.010915
 x' mom.  Cl'|    Cla =  -1.507760    Clb =  -0.046316
 y  mom.  Cm |    Cma =  -0.319576    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.062625    Cnb =   0.002658

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.026884    CLq =   4.687525    CLr =  -0.345906
 y  force CY |    CYp =   0.085291    CYq =   0.000000    CYr =  -0.004192
 x' mom.  Cl'|    Clp =  -1.518456    Clq =  -1.811209    Clr =   0.183858
 y  mom.  Cm |    Cmp =  -0.246962    Cmq =  -1.239341    Cmr =  -0.000021
 z' mom.  Cn'|    Cnp =  -0.039150    Cnq =   0.072450    Cnr =  -0.013595

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011949
 y  force CY |   CYd01 =  -0.000018   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003260   Cld02 =  -0.004622
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005608
 z' mom.  Cn'|   Cnd01 =  -0.000008   Cnd02 =  -0.000035
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000224
 span eff.   |    ed01 =  -0.000000    ed02 =   0.040307



 Neutral point  Xnp =   0.096484

 Clb Cnr / Clr Cnb  =   1.288655    (  > 1 if spirally stable )
