 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.43750     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00100     Cltot =  -0.09357     Cl'tot =  -0.09337
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.24215     Cntot =   0.00039     Cn'tot =   0.00600

  CLtot =   0.24166
  CDtot =   0.01552
  CDvis =   0.01107     CDind = 0.0044508
  CLff  =   0.24192     CDff  = 0.0040794    | Trefftz
  CYff  =   0.00000         e =    0.9417    | Plane  

   Aileron         =   0.00000
   Elevator        =  -3.38146

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.899241    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.011097
 x' mom.  Cl'|    Cla =  -1.506625    Clb =  -0.049795
 y  mom.  Cm |    Cma =  -0.319606    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.067512    Cnb =   0.003123

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.025240    CLq =   4.686094    CLr =  -0.372987
 y  force CY |    CYp =   0.092099    CYq =   0.000000    CYr =  -0.005049
 x' mom.  Cl'|    Clp =  -1.517689    Clq =  -1.810656    Clr =   0.198048
 y  mom.  Cm |    Cmp =  -0.246985    Cmq =  -1.238998    Cmr =  -0.000022
 z' mom.  Cn'|    Cnp =  -0.042211    Cnq =   0.078098    Cnr =  -0.014476

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011941
 y  force CY |   CYd01 =  -0.000019   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003258   Cld02 =  -0.004620
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005605
 z' mom.  Cn'|   Cnd01 =  -0.000014   Cnd02 =  -0.000043
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000239
 span eff.   |    ed01 =  -0.000000    ed02 =   0.038129



 Neutral point  Xnp =   0.096495

 Clb Cnr / Clr Cnb  =   1.165332    (  > 1 if spirally stable )
