 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.51560     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00061     Cltot =  -0.09526     Cl'tot =  -0.09507
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.24654     Cntot =   0.00024     Cn'tot =   0.00608

  CLtot =   0.24604
  CDtot =   0.01573
  CDvis =   0.01111     CDind = 0.0046155
  CLff  =   0.24633     CDff  = 0.0042318    | Trefftz
  CYff  =   0.00000         e =    0.9411    | Plane  

   Aileron         =   0.00000
   Elevator        =  -3.45920

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.898471    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.011145
 x' mom.  Cl'|    Cla =  -1.506327    Clb =  -0.050664
 y  mom.  Cm |    Cma =  -0.319615    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.068731    Cnb =   0.003246

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.024809    CLq =   4.685718    CLr =  -0.379751
 y  force CY |    CYp =   0.093799    CYq =   0.000000    CYr =  -0.005274
 x' mom.  Cl'|    Clp =  -1.517488    Clq =  -1.810511    Clr =   0.201591
 y  mom.  Cm |    Cmp =  -0.246991    Cmq =  -1.238907    Cmr =  -0.000022
 z' mom.  Cn'|    Cnp =  -0.042977    Cnq =   0.079508    Cnr =  -0.014706

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011939
 y  force CY |   CYd01 =  -0.000020   CYd02 =  -0.000000
 x' mom.  Cl'|   Cld01 =  -0.003258   Cld02 =  -0.004619
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005604
 z' mom.  Cn'|   Cnd01 =  -0.000016   Cnd02 =  -0.000045
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000242
 span eff.   |    ed01 =  -0.000000    ed02 =   0.037615



 Neutral point  Xnp =   0.096498

 Clb Cnr / Clr Cnb  =   1.138733    (  > 1 if spirally stable )
