 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.59380     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00022     Cltot =  -0.09696     Cl'tot =  -0.09676
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.25094     Cntot =   0.00008     Cn'tot =   0.00616

  CLtot =   0.25043
  CDtot =   0.01595
  CDvis =   0.01116     CDind = 0.0047834
  CLff  =   0.25073     CDff  = 0.0043871    | Trefftz
  CYff  =   0.00000         e =    0.9406    | Plane  

   Aileron         =   0.00000
   Elevator        =  -3.53705

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.897686    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.011194
 x' mom.  Cl'|    Cla =  -1.506024    Clb =  -0.051533
 y  mom.  Cm |    Cma =  -0.319623    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.069950    Cnb =   0.003371

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.024370    CLq =   4.685334    CLr =  -0.386522
 y  force CY |    CYp =   0.095500    CYq =   0.000000    CYr =  -0.005504
 x' mom.  Cl'|    Clp =  -1.517283    Clq =  -1.810362    Clr =   0.205139
 y  mom.  Cm |    Cmp =  -0.246998    Cmq =  -1.238814    Cmr =  -0.000022
 z' mom.  Cn'|    Cnp =  -0.043745    Cnq =   0.080920    Cnr =  -0.014941

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011937
 y  force CY |   CYd01 =  -0.000020   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003257   Cld02 =  -0.004618
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005603
 z' mom.  Cn'|   Cnd01 =  -0.000017   Cnd02 =  -0.000047
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000246
 span eff.   |    ed01 =  -0.000000    ed02 =   0.037112



 Neutral point  Xnp =   0.096501

 Clb Cnr / Clr Cnb  =   1.113547    (  > 1 if spirally stable )
