 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.75000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.00060     Cltot =  -0.10035     Cl'tot =  -0.10015
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -0.25971     Cntot =  -0.00023     Cn'tot =   0.00633

  CLtot =   0.25920
  CDtot =   0.01639
  CDvis =   0.01126     CDind = 0.0051276
  CLff  =   0.25953     CDff  = 0.0047057    | Trefftz
  CYff  =   0.00000         e =    0.9395    | Plane  

   Aileron         =   0.00000
   Elevator        =  -3.69259

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.896075    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.011294
 x' mom.  Cl'|    Cla =  -1.505401    Clb =  -0.053269
 y  mom.  Cm |    Cma =  -0.319641    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.072382    Cnb =   0.003627

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.023469    CLq =   4.684545    CLr =  -0.400040
 y  force CY |    CYp =   0.098897    CYq =   0.000000    CYr =  -0.005978
 x' mom.  Cl'|    Clp =  -1.516863    Clq =  -1.810058    Clr =   0.212222
 y  mom.  Cm |    Cmp =  -0.247011    Cmq =  -1.238623    Cmr =  -0.000022
 z' mom.  Cn'|    Cnp =  -0.045281    Cnq =   0.083738    Cnr =  -0.015422

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011932
 y  force CY |   CYd01 =  -0.000021   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003256   Cld02 =  -0.004617
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005601
 z' mom.  Cn'|   Cnd01 =  -0.000020   Cnd02 =  -0.000051
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000253
 span eff.   |    ed01 =  -0.000000    ed02 =   0.036143



 Neutral point  Xnp =   0.096507

 Clb Cnr / Clr Cnb  =   1.067168    (  > 1 if spirally stable )
