 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  40.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.42913     Cltot =  -0.78999     Cl'tot =  -0.71175
  CYtot =   0.00000     Cmtot =   0.00000
  CZtot =  -2.04455     Cntot =  -0.16581     Cn'tot =   0.38078

  CLtot =   1.84206
  CDtot =   0.98548
  CDvis =   0.72180     CDind = 0.2636827
  CLff  =   2.06332     CDff  = 0.3161040    | Trefftz
  CYff  =   0.00000         e =    0.8840    | Plane  

   Aileron         =   0.00000
   Elevator        = -53.54847

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   2.873018    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.721688
 x' mom.  Cl'|    Cla =  -1.110103    Clb =  -0.314778
 y  mom.  Cm |    Cma =  -0.447264    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.535929    Cnb =   0.281517

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   2.981763    CLq =   3.899782    CLr =  -2.799317
 y  force CY |    CYp =   0.640721    CYq =   0.000000    CYr =  -0.499631
 x' mom.  Cl'|    Clp =  -1.545566    Clq =  -1.506834    Clr =   1.478462
 y  mom.  Cm |    Cmp =  -0.345636    Cmq =  -1.089414    Cmr =   0.023671
 z' mom.  Cn'|    Cnp =  -0.309051    Cnq =   0.918545    Cnr =  -1.098381

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.007204
 y  force CY |   CYd01 =  -0.000111   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.002248   Cld02 =  -0.003251
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.003567
 z' mom.  Cn'|   Cnd01 =  -0.000387   Cnd02 =  -0.000456
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.001149
 span eff.   |    ed01 =  -0.000000    ed02 =   0.004665



 Neutral point  Xnp =   0.108001

 Clb Cnr / Clr Cnb  =   0.830697    (  > 1 if spirally stable )
