 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: QM-3E                                                       
     # Surfaces =   6
     # Strips   =  60
     # Vortices = 600

  Sref = 0.10430       Cref = 0.15610       Bref = 0.71120    
  Xref = 0.83700E-01   Yref =-0.27480       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.00827     Cltot =  -0.12739     Cl'tot =  -0.12718
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.32969     Cntot =  -0.00319     Cn'tot =   0.00792

  CLtot =   0.32915
  CDtot =   0.02050
  CDvis =   0.01219     CDind = 0.0083104
  CLff  =   0.32988     CDff  = 0.0076558    | Trefftz
  CYff  =   0.00000         e =    0.9330    | Plane  

   Aileron         =   0.00000
   Elevator        =  -4.93970

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.881156    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.012214
 x' mom.  Cl'|    Cla =  -1.499637    Clb =  -0.067105
 y  mom.  Cm |    Cma =  -0.319817    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.091661    Cnb =   0.006029

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   3.015114    CLq =   4.677179    CLr =  -0.507919
 y  force CY |    CYp =   0.125976    CYq =   0.000000    CYr =  -0.010415
 x' mom.  Cl'|    Clp =  -1.512986    Clq =  -1.807212    Clr =   0.268756
 y  mom.  Cm |    Cmp =  -0.247148    Cmq =  -1.236809    Cmr =  -0.000018
 z' mom.  Cn'|    Cnp =  -0.057674    Cnq =   0.106197    Cnr =  -0.019864

                  Aileron      d01     Elevator     d02 
                  ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.011889
 y  force CY |   CYd01 =  -0.000026   CYd02 =   0.000000
 x' mom.  Cl'|   Cld01 =  -0.003247   Cld02 =  -0.004604
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.005584
 z' mom.  Cn'|   Cnd01 =  -0.000045   Cnd02 =  -0.000085
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000310
 span eff.   |    ed01 =  -0.000000    ed02 =   0.029778



 Neutral point  Xnp =   0.096563

 Clb Cnr / Clr Cnb  =   0.822666    (  > 1 if spirally stable )
