 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.11670     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.17632
  CZtot =  -1.52930     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.52634
  CDtot =   0.15063
  CDvis =   0.02029     CDind = 0.1303429
  CLff  =   1.54557     CDff  = 0.1314898    | Trefftz
  CYff  =   0.00000         e =    0.9840    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.120506    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.143112
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.054911
 y  mom.  Cm |    Cma =  -0.731930    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.120961

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.778413    CLr =  -0.000000
 y  force CY |    CYp =   0.188008    CYq =  -0.000000    CYr =   0.237081
 x' mom.  Cl'|    Clp =  -0.368333    Clq =  -0.000000    Clr =   0.335410
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.130823    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.109095    Cnq =   0.000000    Cnr =  -0.172726

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.010225   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000243   CYd02 =  -0.000000   CYd03 =  -0.003235
 x' mom.  Cl'|   Cld01 =  -0.004249   Cld02 =   0.000000   Cld03 =  -0.000213
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.024959   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000387   Cnd02 =   0.000000   Cnd03 =   0.001677
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.001840 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.000434    ed03 =  -0.000000



 Neutral point  Xnp =   0.856281

 Clb Cnr / Clr Cnb  =   0.233774    (  > 1 if spirally stable )
