 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  13.12500     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.20282     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.21515
  CZtot =  -1.74544     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.74590
  CDtot =   0.19883
  CDvis =   0.02741     CDind = 0.1714145
  CLff  =   1.78095     CDff  = 0.1750908    | Trefftz
  CYff  =  -0.00000         e =    0.9812    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.930277    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.125326
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.065635
 y  mom.  Cm |    Cma =  -0.690808    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.126085

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.731578    CLr =  -0.000000
 y  force CY |    CYp =   0.228632    CYq =  -0.000000    CYr =   0.225540
 x' mom.  Cl'|    Clp =  -0.353829    Clq =   0.000000    Clr =   0.372115
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.055992    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.126181    Cnq =   0.000000    Cnr =  -0.191609

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.009940   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000333   CYd02 =  -0.000000   CYd03 =  -0.003201
 x' mom.  Cl'|   Cld01 =  -0.004105   Cld02 =   0.000000   Cld03 =  -0.000203
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.024472   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000350   Cnd02 =   0.000000   Cnd03 =   0.001660
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.002235 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.001113    ed03 =  -0.000000



 Neutral point  Xnp =   0.855139

 Clb Cnr / Clr Cnb  =   0.268049    (  > 1 if spirally stable )
