 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  13.20310     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.20514     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.21609
  CZtot =  -1.75067     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.75125
  CDtot =   0.20014
  CDvis =   0.02764     CDind = 0.1724929
  CLff  =   1.78677     CDff  = 0.1762516    | Trefftz
  CYff  =   0.00000         e =    0.9812    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.925212    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.124933
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.065892
 y  mom.  Cm |    Cma =  -0.689679    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.126225

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.730244    CLr =  -0.000000
 y  force CY |    CYp =   0.229631    CYq =  -0.000000    CYr =   0.225197
 x' mom.  Cl'|    Clp =  -0.353459    Clq =   0.000000    Clr =   0.373000
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.053901    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.126633    Cnq =   0.000000    Cnr =  -0.192111

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.009932   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000336   CYd02 =  -0.000000   CYd03 =  -0.003200
 x' mom.  Cl'|   Cld01 =  -0.004101   Cld02 =   0.000000   Cld03 =  -0.000203
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.024458   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000349   Cnd02 =   0.000000   Cnd03 =   0.001659
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.002245 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.001124    ed03 =  -0.000000



 Neutral point  Xnp =   0.855102

 Clb Cnr / Clr Cnb  =   0.268863    (  > 1 if spirally stable )
