 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  13.75000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.22116     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.22264
  CZtot =  -1.78717     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.78852
  CDtot =   0.20996
  CDvis =   0.02986     CDind = 0.1801077
  CLff  =   1.82742     CDff  = 0.1844735    | Trefftz
  CYff  =   0.00000         e =    0.9806    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.889404    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.122751
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.067672
 y  mom.  Cm |    Cma =  -0.680299    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.129222

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.720613    CLr =  -0.000000
 y  force CY |    CYp =   0.236605    CYq =  -0.000000    CYr =   0.222704
 x' mom.  Cl'|    Clp =  -0.350925    Clq =   0.000000    Clr =   0.379136
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.037782    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.135728    Cnq =   0.000000    Cnr =  -0.189639

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.009875   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000351   CYd02 =  -0.000000   CYd03 =  -0.003191
 x' mom.  Cl'|   Cld01 =  -0.004060   Cld02 =   0.000000   Cld03 =  -0.000201
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.024359   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000401   Cnd02 =   0.000000   Cnd03 =   0.001655
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.002312 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.001200    ed03 =  -0.000000



 Neutral point  Xnp =   0.854615

 Clb Cnr / Clr Cnb  =   0.261942    (  > 1 if spirally stable )
