 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  15.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.25330     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.23745
  CZtot =  -1.87055     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.87238
  CDtot =   0.23947
  CDvis =   0.04156     CDind = 0.1979027
  CLff  =   1.91969     CDff  = 0.2038661    | Trefftz
  CYff  =   0.00000         e =    0.9791    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.805865    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.124387
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.071602
 y  mom.  Cm |    Cma =  -0.658249    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.131534

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.696438    CLr =  -0.000000
 y  force CY |    CYp =   0.252419    CYq =  -0.000000    CYr =   0.216400
 x' mom.  Cl'|    Clp =  -0.345812    Clq =   0.000000    Clr =   0.392715
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -8.993672    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.142969    Cnq =   0.000000    Cnr =  -0.199610

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.009738   CLd03 =  -0.000000
 y  force CY |   CYd01 =  -0.000384   CYd02 =  -0.000000   CYd03 =  -0.003171
 x' mom.  Cl'|   Cld01 =  -0.003994   Cld02 =   0.000000   Cld03 =  -0.000197
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.024103   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000395   Cnd02 =   0.000000   Cnd03 =   0.001645
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.002461 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.001340    ed03 =  -0.000000



 Neutral point  Xnp =   0.853419

 Clb Cnr / Clr Cnb  =   0.276691    (  > 1 if spirally stable )
