 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  16.25000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.29928     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.32867
  CZtot =  -1.71789     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.73301
  CDtot =   0.19340
  CDvis =   0.02658     CDind = 0.1668131
  CLff  =   1.78532     CDff  = 0.1782225    | Trefftz
  CYff  =  -0.00000         e =    0.9687    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.491829    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.135159
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.056147
 y  mom.  Cm |    Cma =  -0.775988    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.130035

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.312078    CLr =   0.000000
 y  force CY |    CYp =   0.223086    CYq =   0.000000    CYr =   0.221324
 x' mom.  Cl'|    Clp =  -0.324839    Clq =   0.000000    Clr =   0.360854
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.122890    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.143141    Cnq =   0.000000    Cnr =  -0.187051

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.009551   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000400   CYd02 =  -0.000000   CYd03 =  -0.003152
 x' mom.  Cl'|   Cld01 =  -0.003539   Cld02 =  -0.000000   Cld03 =  -0.000194
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.023897   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000444   Cnd02 =   0.000000   Cnd03 =   0.001636
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.002467 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.002384    ed03 =   0.000000



 Neutral point  Xnp =   0.883593

 Clb Cnr / Clr Cnb  =   0.223817    (  > 1 if spirally stable )
