 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  16.87500     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.32004     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.33724
  CZtot =  -1.75344     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.77084
  CDtot =   0.20273
  CDvis =   0.02843     CDind = 0.1743007
  CLff  =   1.82773     CDff  = 0.1869882    | Trefftz
  CYff  =  -0.00000         e =    0.9677    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.451872    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.132743
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.057605
 y  mom.  Cm |    Cma =  -0.763668    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.131258

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.304807    CLr =   0.000000
 y  force CY |    CYp =   0.230368    CYq =  -0.000000    CYr =   0.218487
 x' mom.  Cl'|    Clp =  -0.322102    Clq =   0.000000    Clr =   0.367030
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.104447    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.147007    Cnq =   0.000000    Cnr =  -0.190413

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.009475   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000413   CYd02 =  -0.000000   CYd03 =  -0.003139
 x' mom.  Cl'|   Cld01 =  -0.003508   Cld02 =  -0.000000   Cld03 =  -0.000192
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.023757   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000441   Cnd02 =   0.000000   Cnd03 =   0.001630
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.002536 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =  -0.002403    ed03 =   0.000000



 Neutral point  Xnp =   0.882983

 Clb Cnr / Clr Cnb  =   0.227683    (  > 1 if spirally stable )
