 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  17.34380     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.33587     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.34363
  CZtot =  -1.77971     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.79892
  CDtot =   0.20994
  CDvis =   0.02998     CDind = 0.1799668
  CLff  =   1.85941     CDff  = 0.1936762    | Trefftz
  CYff  =  -0.00000         e =    0.9670    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.421496    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.131081
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.058663
 y  mom.  Cm |    Cma =  -0.755584    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.132222

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.299540    CLr =   0.000000
 y  force CY |    CYp =   0.235813    CYq =  -0.000000    CYr =   0.216331
 x' mom.  Cl'|    Clp =  -0.320048    Clq =   0.000000    Clr =   0.371588
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.099033    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.149946    Cnq =   0.000000    Cnr =  -0.193009

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.009417   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000423   CYd02 =  -0.000000   CYd03 =  -0.003129
 x' mom.  Cl'|   Cld01 =  -0.003485   Cld02 =  -0.000000   Cld03 =  -0.000190
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.023668   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000439   Cnd02 =   0.000000   Cnd03 =   0.001624
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.002588 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =  -0.002413    ed03 =   0.000000



 Neutral point  Xnp =   0.882739

 Clb Cnr / Clr Cnb  =   0.230451    (  > 1 if spirally stable )
