 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  17.42190     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.33852     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.34469
  CZtot =  -1.78406     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.80357
  CDtot =   0.21116
  CDvis =   0.03025     CDind = 0.1809146
  CLff  =   1.86467     CDff  = 0.1947997    | Trefftz
  CYff  =  -0.00000         e =    0.9668    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.416403    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.130817
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.058837
 y  mom.  Cm |    Cma =  -0.753979    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.132958

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.298678    CLr =  -0.000000
 y  force CY |    CYp =   0.236718    CYq =  -0.000000    CYr =   0.215969
 x' mom.  Cl'|    Clp =  -0.319706    Clq =   0.000000    Clr =   0.372342
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.097994    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.152040    Cnq =   0.000000    Cnr =  -0.191615

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.009407   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000425   CYd02 =  -0.000000   CYd03 =  -0.003128
 x' mom.  Cl'|   Cld01 =  -0.003478   Cld02 =  -0.000000   Cld03 =  -0.000190
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.023652   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000449   Cnd02 =   0.000000   Cnd03 =   0.001624
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.002596 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.002414    ed03 =   0.000000



 Neutral point  Xnp =   0.882653

 Clb Cnr / Clr Cnb  =   0.227731    (  > 1 if spirally stable )
