 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  17.50000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.34116     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.34575
  CZtot =  -1.78840     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   1.80822
  CDtot =   0.21242
  CDvis =   0.03055     CDind = 0.1818634
  CLff  =   1.86993     CDff  = 0.1959258    | Trefftz
  CYff  =  -0.00000         e =    0.9667    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.411305    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.130585
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.059009
 y  mom.  Cm |    Cma =  -0.752387    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.133667

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.297817    CLr =   0.000000
 y  force CY |    CYp =   0.237623    CYq =   0.000000    CYr =   0.215606
 x' mom.  Cl'|    Clp =  -0.319367    Clq =   0.000000    Clr =   0.373093
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.096987    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.154064    Cnq =   0.000000    Cnr =  -0.190295

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.009397   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000426   CYd02 =  -0.000000   CYd03 =  -0.003126
 x' mom.  Cl'|   Cld01 =  -0.003470   Cld02 =  -0.000000   Cld03 =  -0.000190
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.023637   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000460   Cnd02 =   0.000000   Cnd03 =   0.001623
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.002605 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.002416    ed03 =   0.000000



 Neutral point  Xnp =   0.882569

 Clb Cnr / Clr Cnb  =   0.225168    (  > 1 if spirally stable )
