 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: MX-9D1                                                      
     # Surfaces =   5
     # Strips   = 140
     # Vortices =2200

  Sref =  1.5652       Cref = 0.61240       Bref =  3.0328    
  Xref = 0.74750       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  20.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.29657     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.29662
  CZtot =  -2.22051     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   2.18803
  CDtot =   0.48077
  CDvis =   0.20763     CDind = 0.2731419
  CLff  =   2.27920     CDff  = 0.2890996    | Trefftz
  CYff  =   0.00000         e =    0.9733    | Plane  

   Aileron         =   0.00000
   Elevator        =   0.00000
   Rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.468432    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.249825
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.084734
 y  mom.  Cm |    Cma =  -0.582224    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.133155

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   6.582844    CLr =  -0.000000
 y  force CY |    CYp =   0.314511    CYq =  -0.000000    CYr =   0.185435
 x' mom.  Cl'|    Clp =  -0.338856    Clq =   0.000000    Clr =   0.439336
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -8.918757    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.157466    Cnq =   0.000000    Cnr =  -0.292094

                  Aileron      d01     Elevator     d02     Rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.009095   CLd03 =  -0.000000
 y  force CY |   CYd01 =  -0.000505   CYd02 =  -0.000000   CYd03 =  -0.003058
 x' mom.  Cl'|   Cld01 =  -0.003803   Cld02 =   0.000000   Cld03 =  -0.000178
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.023044   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000108   Cnd02 =   0.000000   Cnd03 =   0.001586
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.003015 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.001612    ed03 =  -0.000000



 Neutral point  Xnp =   0.850300

 Clb Cnr / Clr Cnb  =   0.423081    (  > 1 if spirally stable )
